name: order_automation
description: order_automation

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  excel: ^2.0.1
  http: ^0.13.5
  html: ^0.15.1
  crypto: ^3.0.2
  intl: ^0.18.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  formz: ^0.4.1
  google_fonts: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_strategy: ^0.2.0
  firebase_core: ^2.4.1
  cloud_functions: ^4.0.7
  cloud_firestore: ^4.3.1
  universal_platform: ^1.0.0+1
  file_picker: ^5.2.5
  flutter_native_splash: ^2.1.1
  flutter_barcode_scanner: ^2.0.0
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/images/splash_image/splash.jpeg
  image_dark: assets/images/splash_image/splash.jpeg
  fullscreen: true
#flutter pub run flutter_native_splash:create
#ios status bar style check!!

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_image/app_icon.jpeg"
#flutter pub run flutter_launcher_icons:main