// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo-cICYPTsF2pIQg3aX571OGL4Due368g',
    appId: '1:640676993733:web:e76bd39e7f0a0f1ca9aeac',
    messagingSenderId: '640676993733',
    projectId: 'order-automation-kr',
    authDomain: 'order-automation-kr.firebaseapp.com',
    storageBucket: 'order-automation-kr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbQBPYZNof8Cu-ITwCERXbtF7EuZ1DuO0',
    appId: '1:640676993733:android:c05e75b5bd6eb931a9aeac',
    messagingSenderId: '640676993733',
    projectId: 'order-automation-kr',
    storageBucket: 'order-automation-kr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQL9mCI4uNJhh8oFguwASZiju9qNXw9_g',
    appId: '1:640676993733:ios:22998d1c2a2540eaa9aeac',
    messagingSenderId: '640676993733',
    projectId: 'order-automation-kr',
    storageBucket: 'order-automation-kr.appspot.com',
    iosClientId: '640676993733-sumkr9al8rptsoan15ubk98rmvsbeq5m.apps.googleusercontent.com',
    iosBundleId: 'com.nomadcat.orderautomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQL9mCI4uNJhh8oFguwASZiju9qNXw9_g',
    appId: '1:640676993733:ios:ef281933333c7f14a9aeac',
    messagingSenderId: '640676993733',
    projectId: 'order-automation-kr',
    storageBucket: 'order-automation-kr.appspot.com',
    iosClientId: '640676993733-ipnv9vpetree4k3knrte2ocfkpliut8k.apps.googleusercontent.com',
    iosBundleId: 'com.nomadcat.orderautomation.orderAutomation',
  );
}
